version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-cloudformation: orbss/aws-cloudformation@0.1.6

parameters:
  NameBase:
    type: string
    default: "lec13"

jobs:
  execute-cfn:
    executor: aws-cloudformation/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - aws-cloudformation/deploy:
          stack-name: "<<pipeline.parameters.NameBase>>-vpc-stack"
          template-file-path: "cloudformation/create-vpc.yml"
      - aws-cloudformation/deploy:
          stack-name: "<<pipeline.parameters.NameBase>>-sg-stack"
          template-file-path: "cloudformation/create-securitygroup.yml"
      - aws-cloudformation/deploy:
          stack-name: "<<pipeline.parameters.NameBase>>-resources-stack"
          template-file-path: "cloudformation/create-resources.yml"
          parameter-overrides: "RDSpassword=$AWS_DB_PW"
          capabilities: CAPABILITY_NAMED_IAM
            
workflows:
  lecture13:
    jobs:
      - execute-cfn
