---
# tasks file for git
- name: install git
  ansible.builtin.yum:
    name: git
    state: present

- name: git clone sample-app
  ansible.builtin.git: 
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: /home/{{ ansible_user }}/raisetech-live8-sample-app
    force: yes
  become: no
