---
- hosts: all
  become: yes
  
  vars:
    ansible_user: ec2-user
    ruby_version: 3.2.3
    bundle_version: 2.3.14
    rails_version: 7.1.3.2
    node_version: 17.9.1
    yarn_version: 1.22.19
    aws_alb_host : "{{ (lookup('env','AWS_ALB_HOST')) }}"
    aws_db_user: "{{ (lookup('env','AWS_DB_USER')) }}"
    aws_db_pw : "{{ (lookup('env','AWS_DB_PW')) }}"
    aws_db_host : "{{ (lookup('env','AWS_DB_HOST')) }}"
    aws_s3_bucket: "{{ (lookup('env','AWS_S3_BUCKET')) }}"

  roles:
    - git
    - ruby
    - bundler
    - rails
    - node
    - yarn
    - mysql
    - bin_setup
    - nginx
    - setup_server
